spring:
  data:
    mongodb:
      username: carolan
      password: carolan
      host: localhost
      port: 27018
      database: chat_app
      authentication-database: admin
server:
  port: 8088
